id: P79823D63
initial_creation_type: ocr
source_metadata:
  volumes:
    18bc17822cdc4e3188848ed78754285b:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: གནོད་པ་སེལ་བའི་བདུད་རྩི།
      total_pages: 1379
      volume_number: 37
